$ANSIBLE_VAULT;1.1;AES256
34633463396665396530346136636239333438653535386264323534396464613762643934613032
3030626163356339353465653834386662363662383230300a356139373432393536383765666133
65353634363934663036323431623063333039386137306637626433343237326536303139326136
6663646532366331640a356232643863333738396163633739613733613265663131353836393064
38323665363535373233613662613037363236303264643334323831373032336531613332613430
33373536333434666630663933356334616333626161666238363365336136393664623338383636
36383238656531373037613838363538663162396133316635323434643736376535336134636266
61326362396231353539313231386666643164306165313736663664373032303734323333663430
62613838613466626632316631353065633963663534633034613361613334373762313939343762
32663765333065353231313734663338393137353334653133656563343032346637633465393161
62653338306339303863663233316264396566303835376634653932663964353932326131643337
39666165343133313430313039313061623334333166613065623339373764313133613133666537
3966
